### ISSUE TITLE
Error installing plugin

### ISSUE THREAD

**Issue by elffikk** [Taracque/ionic-plugin-callkit#12]
cordova plugin add https://github.com/Taracque/ionic-plugin-callkit.git
Error: Failed to fetch plugin https://github.com/Taracque/ionic-plugin-callkit via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 4294963228 Error output:
npm ERR! addLocal Could not install ...\AppData\Local\Temp\npm-6976-5685b142\git-cache-1f5128bf\3bc112b9e6fbc8fedad103b6ff998ce20799cea6
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/Taracque/ionic-plugin-callkit" "--save"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code EISDIR
npm ERR! errno -4068
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

**Comment by Taracque** [comment]
Please try to add it with `cordova plugin add https://github.com/Taracque/ionic-plugin-callkit.git --verbose` and post the error logs here.

**Comment by elffikk** [comment]
cordova plugin add https://github.com/Taracque/ionic-plugin-callkit.git --verbose
No scripts found for hook "before_plugin_add".
Calling plugman.fetch on plugin "https://github.com/Taracque/ionic-plugin-callkit.git"
saving
Running command: cmd "/s /c ""C:\Program Files\nodejs\npm.cmd" install https://github.com/Taracque/ionic-plugin-callkit.git --save""
Command finished with error code 4294963228: cmd /s /c ""C:\Program Files\nodejs\npm.cmd" install https://github.com/Taracque/ionic-plugin-callkit.git --save"
Error: Failed to fetch plugin https://github.com/Taracque/ionic-plugin-callkit.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 4294963228 Error output:
npm ERR! addLocal Could not install ...\AppData\Local\Temp\npm-6712-8d9a3445\git-cache-ab7e569d\3bc112b9e6fbc8fedad103b6ff998ce20799cea6
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/Taracque/ionic-plugin-callkit.git" "--save"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code EISDIR
npm ERR! errno -4068
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     ...\node_modules\npm-debug.log

**Comment by elffikk** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'https://github.com/Taracque/ionic-plugin-callkit.git',
1 verbose cli   '--save' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData https://github.com/Taracque/ionic-plugin-callkit.git
8 silly fetchOtherPackageData https://github.com/Taracque/ionic-plugin-callkit.git
9 silly cache add args [ 'https://github.com/Taracque/ionic-plugin-callkit.git', null ]
10 verbose cache add spec https://github.com/Taracque/ionic-plugin-callkit.git
11 silly cache add parsed spec Result {
11 silly cache add   raw: 'https://github.com/Taracque/ionic-plugin-callkit.git',
11 silly cache add   scope: null,
11 silly cache add   escapedName: null,
11 silly cache add   name: null,
11 silly cache add   rawSpec: 'https://github.com/Taracque/ionic-plugin-callkit.git',
11 silly cache add   spec: 'git+https://github.com/Taracque/ionic-plugin-callkit.git',
11 silly cache add   type: 'hosted',
11 silly cache add   hosted:
11 silly cache add    { type: 'github',
11 silly cache add      ssh: 'git@github.com:Taracque/ionic-plugin-callkit.git',
11 silly cache add      sshUrl: 'git+ssh://git@github.com/Taracque/ionic-plugin-callkit.git',
11 silly cache add      httpsUrl: 'git+https://github.com/Taracque/ionic-plugin-callkit.git',
11 silly cache add      gitUrl: 'git://github.com/Taracque/ionic-plugin-callkit.git',
11 silly cache add      shortcut: 'github:Taracque/ionic-plugin-callkit',
11 silly cache add      directUrl: 'https://raw.githubusercontent.com/Taracque/ionic-plugin-callkit/master/package.json' } }
12 verbose addRemoteGit caching https://github.com/Taracque/ionic-plugin-callkit.git
13 verbose addRemoteGit git+https://github.com/Taracque/ionic-plugin-callkit.git is a repository hosted by github
14 silly tryClone cloning git+https://github.com/Taracque/ionic-plugin-callkit.git via git+https://github.com/Taracque/ionic-plugin-callkit.git
15 verbose tryClone git-https-github-com-Taracque-ionic-plugin-callkit-git-335375b3 not in flight; caching
16 verbose correctMkdir ...\AppData\Roaming\npm-cache\_git-remotes correctMkdir not in flight; initializing
17 info git [ 'config', '--get', 'remote.origin.url' ]
18 silly validateExistingRemote git+https://github.com/Taracque/ionic-plugin-callkit.git remote.origin.url: https://github.com/Taracque/ionic-plugin-callkit.git
19 verbose validateExistingRemote git+https://github.com/Taracque/ionic-plugin-callkit.git is updating existing cached remote ...\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-Taracque-ionic-plugin-callkit-git-335375b3
20 info git [ 'fetch', '-a', 'origin' ]
21 verbose updateRemote git fetch -a origin (https://github.com/Taracque/ionic-plugin-callkit.git)
22 verbose setPermissions git+https://github.com/Taracque/ionic-plugin-callkit.git skipping chownr on Windows
23 verbose resolveHead git+https://github.com/Taracque/ionic-plugin-callkit.git original treeish: master
24 info git [ 'rev-list', '-n1', 'master' ]
25 silly resolveHead git+https://github.com/Taracque/ionic-plugin-callkit.git resolved treeish: 3bc112b9e6fbc8fedad103b6ff998ce20799cea6
26 verbose resolveHead git+https://github.com/Taracque/ionic-plugin-callkit.git resolved Git URL: git+https://github.com/Taracque/ionic-plugin-callkit.git#3bc112b9e6fbc8fedad103b6ff998ce20799cea6
27 silly resolveHead Git working directory: ...\AppData\Local\Temp\npm-5592-ff709d5e\git-cache-9d51fc70\3bc112b9e6fbc8fedad103b6ff998ce20799cea6
28 info git [ 'clone',
28 info git   '...\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-https-github-com-Taracque-ionic-plugin-callkit-git-335375b3',
28 info git   '...\\AppData\\Local\\Temp\\npm-5592-ff709d5e\\git-cache-9d51fc70\\3bc112b9e6fbc8fedad103b6ff998ce20799cea6' ]
29 verbose cloneResolved git+https://github.com/Taracque/ionic-plugin-callkit.git clone Cloning into '...\AppData\Local\Temp\npm-5592-ff709d5e\git-cache-9d51fc70\3bc112b9e6fbc8fedad103b6ff998ce20799cea6'...
29 verbose cloneResolved done.
30 info git [ 'checkout', '3bc112b9e6fbc8fedad103b6ff998ce20799cea6' ]
31 verbose checkoutTreeish git+https://github.com/Taracque/ionic-plugin-callkit.git checkout Note: checking out '3bc112b9e6fbc8fedad103b6ff998ce20799cea6'.
31 verbose checkoutTreeish
31 verbose checkoutTreeish You are in 'detached HEAD' state. You can look around, make experimental
31 verbose checkoutTreeish changes and commit them, and you can discard any commits you make in this
31 verbose checkoutTreeish state without impacting any branches by performing another checkout.
31 verbose checkoutTreeish
31 verbose checkoutTreeish If you want to create a new branch to retain commits you create, you may
31 verbose checkoutTreeish do so (now or later) by using -b with the checkout command again. Example:
31 verbose checkoutTreeish
31 verbose checkoutTreeish   git checkout -b <new-branch-name>
31 verbose checkoutTreeish
31 verbose checkoutTreeish HEAD is now at 3bc112b... Merge pull request #8 from VadimDez/master
32 info git [ 'submodule', '-q', 'update', '--init', '--recursive' ]
33 verbose updateSubmodules git+https://github.com/Taracque/ionic-plugin-callkit.git submodule update
34 error addLocal Could not install ...\AppData\Local\Temp\npm-5592-ff709d5e\git-cache-9d51fc70\3bc112b9e6fbc8fedad103b6ff998ce20799cea6
35 silly fetchPackageMetaData Error: EISDIR: illegal operation on a directory, read
35 silly fetchPackageMetaData     at Error (native)
35 silly fetchPackageMetaData  error for https://github.com/Taracque/ionic-plugin-callkit.git { Error: EISDIR: illegal operation on a directory, read
35 silly fetchPackageMetaData     at Error (native) errno: -4068, code: 'EISDIR', syscall: 'read' }
36 silly rollbackFailedOptional Starting
37 silly rollbackFailedOptional Finishing
38 silly runTopLevelLifecycles Finishing
39 silly install printInstalled
40 verbose stack Error: EISDIR: illegal operation on a directory, read
40 verbose stack     at Error (native)
41 verbose cwd D:\vue-dev\caller01\node_modules
42 error Windows_NT 10.0.14393
43 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/Taracque/ionic-plugin-callkit.git" "--save"
44 error node v6.9.5
45 error npm  v3.10.10
46 error code EISDIR
47 error errno -4068
48 error syscall read
49 error eisdir EISDIR: illegal operation on a directory, read
50 error eisdir This is most likely not a problem with npm itself
50 error eisdir and is related to npm not being able to find a package.json in
50 error eisdir a package you are trying to install.
51 verbose exit [ -4068, true ]

**Comment by Taracque** [comment]
Can you add other plugins from github?

**Comment by elffikk** [comment]
yes, just tested 
cordova plugin add https://github.com/floatinghotpot/cordova-plugin-sms

**Comment by alu** [comment]
@Taracque 

Thanks for good plugin.

This issue happen on cordova 7 because package.json is required.

https://cordova.apache.org/news/2017/05/04/cordova-7.html

**Comment by Taracque** [comment]
Thanks for the feedback. I've added the package.json file, can you please make a try?

**Comment by alu** [comment]
@Taracque 

It's successfully on Cordova 7.0.1.

Thanks!
