### ISSUE TITLE
Fallback to pushkit

### ISSUE THREAD

**Issue by ghost** [Taracque/ionic-plugin-callkit#16]
I know that you actually already made a pushkit plugin called VoIP Push, so why not integrate into this plugin as a fallback?

**Comment by Taracque** [comment]
Push is not a requirement for callkit. You can use other ways for signaling. There are also a lot of push solutions for cordova, and each can be used. Also my Voip push plugin is iOs only.

**Comment by ghost** [comment]
That's actually what I meant. Apple's term for VoIP push is PushKit, even though it's not actually a push notification https://developer.apple.com/reference/pushkit. Figured it would be cool to have as a fallback integrated here for iOS 8-9 support, since you are the creator of both awesome plugins :)

**Comment by Taracque** [comment]
Both plugins can be used without the other one. So maintaining the pushkit part in 2 places is more dificult than installing 2 plugins in a project.

**Comment by ghost** [comment]
That makes sense, I just assumed that CallKit superseded PushKit (and that PushKit is only used for fallback), but I guess some people may still prefer to use PushKit as well. Thank you for the reply and making such a great plugin!
