### ISSUE TITLE
display video view on iosApp upon call accept

### ISSUE THREAD

**Issue by skumarcm** [Taracque/ionic-plugin-callkit#22]
First of all.. Thank you very much for this fantastic plugin making it easier to integrate the callKit.
I could successfully integrate my cordova App with this plugin in iOS platform.

I was able to bring up the incoming call screen when a call is received and was able to accept the call and start talking with the caller. Further, I was able to display the video when the user clicks on the app icon on the call screen.

My question:
========
Can we display the video immediately after the user accepts the call without the need for the user to click on the app icon? If not, the user may not notice that the call is a video call and continue with the audio call only.

**Comment by Taracque** [comment]
No, unfortunately this is a CallKit limitation, user needs to press the button to bring application to the foreground.

**Comment by skumarcm** [comment]
Fair enough.. Thank you very much for your response.
