### ISSUE TITLE
incoming call question

### ISSUE THREAD

**Issue by Newlik** [Taracque/ionic-plugin-callkit#3]
Hi @Taracque ,

Great plugin!
I would like to ask about "callChanged" function of CallKit.register.
Is it detect every incoming call (like if somebody calling my phone from another phone) or just the plugin managed calls (if i call the myCallKit.startCall(name,isVideo,onSuccess) method ) ?

Thank You :)

**Comment by Taracque** [comment]
It is only for reportIncominCall. (Called when user accepts or declines call on the native callscreen) There is no way to intercept non your own calls.

**Comment by Newlik** [comment]
thank you :)
